#Adobe Granite License Properties
#Mon Jun 18 10:44:59 UTC 2018
license.product.name=Adobe Experience Manager
license.customer.name=Adobe Internal
license.product.version=6.4.0
license.downloadID=cafebabe-cafe-0246-8756-0ddcce804709
